### ISSUE TITLE
¿De qué podemos hacer el trabajo?

### ISSUE THREAD

**Issue by LinceIberico** [LinceIberico/Trabajo-GitHub#1]
Bueno, pues comienzo con la pregunta jaja.

He pensado que podríamos hacer una página web, algo que todos más o menos controlamos mejor y no es tan complejo como una aplicación java o similar.

A ver qué comentáis y vemos la temática y como podemos hacerla si os parece bien.

**Comment by Draconary** [comment]
Por mi, podríamos hacer una web. Os parece de una tienda??

**Comment by bruno259825** [comment]
Me parece muy bien Daniel, podríamos hacer antes que todo un diseño básico de la web, con un boceto en paint bastaría.

**Comment by Juanjose13** [comment]
Me parece buena idea lo de hacer una página web, ya solo tendríamos que concretar el tema de la web

**Comment by LinceIberico** [comment]
> Me parece muy bien Daniel, podríamos hacer antes que todo un diseño básico de la web, con un boceto en paint bastaría. 

Se te da bien el Paint? 
Si quieres puedes hacer un boceto simple con una página principal. Otra de los productos ( podríamos vender como si fuéramos una inmobiliaria) unas cuentas fotos de Casas y eso. 
Y otra de contacto.

**Comment by carlosmunioz99** [comment]
Si, lo suyo es hacer una pagina web, porque es lo que mas controlamos. La temática la verdad que me da igual pero para que haya más páginas lo mejor creo que es la idea de la tienda y así tenemos distintos archivos HTML de los que encargarnos cada uno y hacer todos el mismo peso de trabajo.

**Comment by bruno259825** [comment]
> > Me parece muy bien Daniel, podríamos hacer antes que todo un diseño básico de la web, con un boceto en paint bastaría. 
> 
> Se te da bien el Paint? 
> Si quieres puedes hacer un boceto simple con una página principal. Otra de los productos ( podríamos vender como si fuéramos una inmobiliaria) unas cuentas fotos de Casas y eso. 
> Y otra de contacto.

Vale, yo me encargo de hacer el boceto de la página principal.

**Comment by bruno259825** [comment]
Chavales acabo de subir un directorio con el diseño a la rama principal.

**Comment by LinceIberico** [comment]
> Chavales acabo de subir un directorio con el diseño a la rama principal.

Está muy bien, si queréis hago el cuerpo en html, y los subo. 
Qué alguno busque imágenes o piense los textos.
En cuanto ponga los html vamos haciendo entre todos el CSS que tiene más mandanga.

**Comment by Juanjose13** [comment]
> > Chavales acabo de subir un directorio con el diseño a la rama principal.
> 
> Está muy bien, si queréis hago el cuerpo en html, y los subo.
> Qué alguno busque imágenes o piense los textos.
> En cuanto ponga los html vamos haciendo entre todos el CSS que tiene más mandanga.

Vale, vamos buscando las imágenes y después nos centramos en el css.

**Comment by Draconary** [comment]
Oído cocina. Voy buscando imágenes también

**Comment by Draconary** [comment]
> Chavales acabo de subir un directorio con el diseño a la rama principal.

Veo bien el boceto. Fácil de entender y de plasmar luego
