### ISSUE TITLE
Mini Tutorial para GitHub

### ISSUE THREAD

**Issue by LinceIberico** [LinceIberico/Trabajo-GitHub#2]
Os dejo este enlace de YouTube, lo explica bien y parece que será asi como lo tendremos que hacer.

https://www.youtube.com/watch?v=hWglK8nWh60&feature=emb_rel_pause

**Comment by Draconary** [comment]
Thanks. Ahora toca ponerse

**Comment by LinceIberico** [comment]
Os pongo un pequeño resumen;

Podeís darle desde el proyecto donde pone "CODE" el boton de color verde, podeís darle a abrir desde el Git Desktop, eso si lo tenéis instalados os abrirá el programa.

Luego si tenéis el Visual Studio, podeís abrir el proyecto para editar y crear como hacemos normalmente.

Cuando tengamos hecho lo que queramos dando a Ctrol + Ñ a la vez, nos aparece la terminal del visual, ahí podemos darle a los siguientes comandos:

git status -s  => esto nos muestra el estado en el que se encuentran nuestros archivos.
git init => para iniciar, aunque si habéis hecho lo anterior, no hace falta.
git add index.html => esto añadiría temporalmente el archivo que le hayamos pasado. En este caso el index.html. 
Una vez hecho el **git add** hay que hacer 
git commit -m "AQUI PONEIS LO QUE VEAIS OPORTUNO" => esto es muy importante hacerlo, pues es los comentarios que nos aparecerán después en los archivos que hemos ido subiendo o modificando.

Después desde el programa de Git Desktop os va a aparecer que debéis hacer push.. con darle desde ahí se sube al repositorio online. Os debe aparecer ya en el navegador y en la app del teléfono.

**Comment by LinceIberico** [comment]
Cierro el manual.
