### ISSUE TITLE
Duda sobre color de fondo

### ISSUE THREAD

**Issue by Draconary** [LinceIberico/Trabajo-GitHub#3]
Una pregunta. Qué color de fondo queremos darle a la web?
Había pensado en que un tono blanco, marfil o un tono parecido podría venirle bien. Lo que vendría siendo un tono sobrio

**Comment by LinceIberico** [comment]
Pues si me parece bien. 
yo en cuanto tenga un rato pongo el esqueleto del Index.

**Comment by Juanjose13** [comment]
Me parece bien ese color, pega con la temática de la web.
