### ISSUE TITLE
Branch CSS creada

### ISSUE THREAD

**Issue by Draconary** [LinceIberico/Trabajo-GitHub#5]
Hola. He creado una nueva branch en la que he añadido código CSS. AL ver que no daba conflicto con la principal la he añadido a la branch principal.

Confirmad si podéis que va bien

**Comment by Juanjose13** [comment]
Perfecto Dani, he metido mas líneas en el CSS , esto va cogiendo forma.

**Comment by LinceIberico** [comment]
Voy cerrando por aqui, está de momento todo actualizado.
