### ISSUE TITLE
Creación de la web contacto.html y de su estilo

### ISSUE THREAD

**Issue by carlosmunioz99** [LinceIberico/Trabajo-GitHub#7]
Buenas, he creado una branch para añadir la web de contacto y he modificado el estilo de esta en el archivo CSS.
Os adjunto la referencia del branch en cuestión #6

**Comment by LinceIberico** [comment]
Gracias Carlos, lo que no he visto como subir la carpeta con las imagenes. A ver si Bruno sabe como subir lo que es una carpeta entera con sus archivos dentro.

**Comment by carlosmunioz99** [comment]
Vale, yo creo que se como es, se me había ido por completo que tenía que subirla. Ahora en un momento la subo!

**Comment by carlosmunioz99** [comment]
Listo, la carpeta de las imagenes ya esta subida, creo una carpeta también para meter el css y tenerlo todo mas organizado.

**Comment by LinceIberico** [comment]
Cierro aquí, esta todo ok y he ido haciendo los merge que quedaban.
